\documentclass[]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%
\usepackage[hyphens]{url}

  \journal{CMAJ Open} % Sets Journal name


\usepackage{lineno} % add
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\usepackage{graphicx}
\usepackage{booktabs} % book-quality tables
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\bibliographystyle{elsarticle-harv}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Vaccination of Front-Line Workers with the AstraZeneca COVID-19 Vaccine: Benefits in the Face of Increased Risk for Prothrombotic Thrombocytopenia},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls

\setcounter{secnumdepth}{0}
% Pandoc toggle for numbering sections (defaults to be off)
\setcounter{secnumdepth}{0}

% Pandoc citation processing
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[3] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc} % for calculating minipage widths
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

% Pandoc header
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{threeparttable}
\usepackage{rotating}
\usepackage[utf8]{inputenc}
\def\tightlist{}




\begin{document}
\begin{frontmatter}

  \title{Vaccination of Front-Line Workers with the AstraZeneca COVID-19
Vaccine: Benefits in the Face of Increased Risk for Prothrombotic
Thrombocytopenia}
    \author[UBC]{Amin Adibi\corref{1}}
   \ead{amin.adibi@ubc.ca} 
    \author[Sinai,Microb]{Mohammad Mozafarihashjin}
   \ead{mohammad.mozafarihashjin@sinaihealth.ca} 
    \author[UBC]{Mohsen Sadatsafavi}
   \ead{msafavi@mail.ubc.ca} 
      \address[UBC]{Respiratory Evaluation Sciences Program,
Collaboration for Outcomes Research and Evaluation (CORE), Faculty of
Pharmaceutical Sciences, University of British Columbia, Vancouver,
British Columbia}
    \address[Sinai]{Lunenfeld-Tanenbaum Research Institute, Sinai Health
System, Toronto, Ontario}
    \address[Microb]{Department of Microbiology, Sinai Health System,
Toronto, Ontario}
      \cortext[1]{Corresponding Author}
  
  \begin{abstract}
  \textbf{Background:} Recently, National Advisory Committee on
  Immunization (NACI) recommended against using the AstraZeneca COVID-19
  vaccine in younger adults pending further review of the risk for
  vaccine-induced prothrombotic immune thrombocytopenia (VIPIT). In
  response, British Columbia (BC) halted its front-line workers
  vaccination program. It remains unclear whether the alternative mRNA
  vaccines can be immediately made available to front-line workers.

  \textbf{Methods:} Using latest evidence and compartmental modelling,
  we compared \emph{1)} expected number of deaths due to COVID-19 and
  VIPIT under the scenarios of immediately continuing vaccination of
  front-line workers with the AstraZeneca vaccine or delaying it in
  favour of mRNA vaccines from a societal perspective, and \emph{2)} the
  mortality risk of immediately receiving the AstraZeneca vaccine with
  waiting to receive an mRNA vaccine later from a personal perspective.

  \textbf{Results:} If BC restart the front-line worker vaccination
  program, we expect to see approximately 45,000 fewer cases of
  COVID-19, 800 fewer hospitalizations, 120 fewer COVID-related deaths,
  and 2,300 fewer cases of Long COVID, for an expected number of
  VIPIT-related deaths of 0.674 {[}95\% CI 0.414-0.997{]}. In high-risk
  areas, delayed vaccination with mRNA vaccines led to 3.5-4.5 times
  higher excess mortality risk for those between 30 and 69 years of age.
  For those under 30, the AstraZeneca vaccine posed a higher risk than
  delayed vaccination with mRNA vaccines.

  \textbf{Interpretation:} The benefits of continuing immunization of
  front-line workers with the AstraZeneca vaccine far outweigh the risk
  both from a societal and a personal perspective for those over 40, and
  those over 30 in high-risk areas.
  \end{abstract}
  
 \end{frontmatter}

\hypertarget{background}{%
\section{Background}\label{background}}

On March 29th, 2021, Canada's National Advisory Committee on
Immunization (NACI) recommended against using the AstraZeneca (AZ)
COVID-19 Vaccine for Canadians under the age of 55, due to concerns
about vaccine-induced prothrombotic immune thrombocytopenia (VIPIT)
based on European reports {[}1--3{]}. On March 18th, 2021, the European
Medicines Agency estimated the incidence of VIPIT at approximately 1 per
1,000,000 people vaccinated with the AZ vaccine {[}4{]}. A higher
estimated rate of 1 per 100,000 by the Paul-Ehrlich Institut in Germany
was published on March 19th {[}5{]}. It was this higher rate reported by
the Paul-Ehrlich Institut (PEI) that led NACI to recommend against using
this vaccine in adults under 55 years old {[}1{]}.

On April 1st, the UK Medicines \& Healthcare Products Regulatory Agency
(MHRA) updated its own previously reported data to report a total of 22
cerebral venous sinus thrombosis (CVST) and 8 other clot-related events
from 18.1 million doses of the AZ vaccine (total incidence rate 1 in
600,000) {[}6{]}. On April 7th, MHRA concluded a possible link between
the AZ vaccine and extremely rare clotting events and updated its data
to report 79 UK cases of VIPIT (51 in women and 28 in men, all of them
between 18 to 79 years old), including 44 cases of CVST and 35 cases of
thrombosis in other major veins (incidence rate 1 in 250,000){[}7{]}.

On the same day, the Pharmacovigilance Risk Assessment Committee (PRAC)
of the European Medicines Agency (EMA) concluded that VIPIT should be
listed as a very rare side effect of the AZ vaccine. PRAC noted that as
of March 22nd, a total of 86 cases of VIPIT (62 cases of CVST and 24
cases of splanchnic vein thrombosis) and 18 fatalities out of about 25
million vaccine doses were reported in EudraVigilance, the EU drug
safety database {[}8{]}. As of April 4th, 2021, 222 cases of VIPIT (169
cases of CVST and 53 cases of splanchnic vein thrombosis) had been
reported to EudraVigilance out of around 34 million people who had
received the AZ vaccine {[}8{]}.

BC had initially slated the AZ vaccine for outbreak control and
front-line workers vaccination program. On March 29th and following
NACI's recommendation, BC paused using the AZ vaccine for those under 60
and put the front-line workers vaccination program on hold.

Canadian provinces received 1.5 million doses of the AZ vaccine from the
US and another 316,800 doses from the COVAX program in between the two
weeks period ending on April 11th {[}9{]}. British Columbia received
246,700 doses from these two AZ deliveries, enough to finish providing
the first dose to all remaining front-line workers.

The 300,690 doses of Pfizer-BioNTech and 105,900 doses of Moderna
vaccines expected within the same time frame are currently allocated for
the priority groups, indigenous population, and the currently ongoing
age-based vaccination campaign. The AZ vaccine was initially allocated
to front-line workers due to its easier handling and storage
requirements. If it is not logistically possible to switch the vaccine
allocation for above 55 years old age groups to the AZ vaccine and use
either Pfizer-BioNTech or Moderna vaccines for younger front-line
workers without delay, one might ask whether the benefits of immediately
deploying the AZ vaccine for front-line workers outweigh the rare but
serious risk for VIPIT.

Here, we provide a preliminary harm-benefit analysis of immediate
vaccination of all front-line workers with the AZ COVID-19 vaccine. We
based our analysis on mortality alone, and explore the risk both from a
societal and individual risk perspective.

\hypertarget{methods}{%
\section{Methods}\label{methods}}

We assumed that BC allocates all 246,700 doses to front-line workers and
that there is enough uptake that BC is able to administer all these
doses. We compared immediately prioritizing front-line workers for the
AZ vaccine (\emph{Scenario A}) and asking them to wait to receive mRNA
vaccines as part of the current age-based program (\emph{Scenario B}).
For harm-benefit analysis from a societal perspective, we compared
expected number of deaths under each vaccination strategy.

We estimated the expected number of deaths due to VIPIT as
\(E(death)_{VIPIT} = d \times P(VIPIT|vaccine) \times P(death|VIPIT)\),
where \(d\) is the number of doses administered, \(P(VIPIT|vaccine)\) is
the risk of VIPIT after receiving each dose of the AZ vaccine, and
\(P(death|VIPIT)\) is the case fatality for VIPIT. We did a
probabilistic analysis in which appropriate probability distributions
were assigned to model parameters for which relevant data were
available.

We assumed that each dose of the vaccine is independently associated
with the risk for VIPIT and that the risk of VIPIT is uniform across all
age groups. The most recent estimate for these probabilities by EMA, and
the estimates NACI used in its calculations are summarized in Table 1.

We estimated the benefits of the AZ COVID-19 vaccine using a BC-specific
age-structured COVID-19 compartmental model by Mulberry and colleagues
that takes into account transmission, age-based contact structure,
front-line worker status, and rising \(R_0\) due to variants of concern
{[}10{]}. The model included susceptible, exposed, infectious and
recovered (SEIR) status and was based on the transmission model by Bubar
et al {[}11{]}.

We ran the model from January 2021 to September 2021, which is when the
vaccination campaign is expected to conclude. To follow BC vaccination
strategy and case counts in the first three months of 2021, we held
\(R_0\) at 1.03 from January 1, 2021 for 70 days during which people
over 80 years old were eligible for vaccination. Age groups that were
offered vaccination were considered to be vaccinated at a steady pace
until everyone who is not vaccine-hesitant is vaccinated. Around the end
of March, we raised \(R_0\) to either 1.15 or 1.35 to account for
variants of concern gaining a foothold in BC and increased the pace of
the vaccination program. We validated these assumptions by comparing
model projections under these values against observed case counts for
the January 1st to April 15th, 2021 period.

\begin{sidewaystable}
\caption{Harm-benefit parameters and model assumptions}
{\begin{tabular}{llllll} \toprule
 & \multicolumn{2}{l}{Estimates} \\ \cmidrule{2-6}
 Variable & EMA & EMA  & NACI  \\
  & Base Value & Probability Distribution & Base Value \\ \midrule
 $P(\text{VIPIT}|\text{vaccine})$ & 1 in 153,000 & $\beta(222, 3.4\times 10^7)$ & 1 in 100,000 \\
 $P(\text{death}|\text{VIPIT})$ & $21\%$ &  $\beta(18, 86-18)$ & $40\%$ \\ \\
 & \multicolumn{2}{l}{Assumptions} \\ \cmidrule{2-6}
 Parameter  & Base Value & Sensitivity & \\ \midrule
 $R_0$ & 1.35 & 1.15, 1.5 &  \\ 
 $v_e$ & 0.60 & 0.60, 0.75, 0.90 &  \\ 
 $v_p$ & 0.80 & 0.60, 0.90 &  \\ \\
 
  & \multicolumn{2}{l}{Population Parameters} \\ \cmidrule{2-6}
  Age  Group & Hospitalization & Death   & Long COVID & Vaccine Hesitancy & Front-Line Workers \\ 
             & Rate            & Rate    & Rate       & \% of Population & \% of Population \\ 

  \midrule
Under 20   & 0.0062    & 0       & 0.04       & NA                & 0           \\ 
20-29      & 0.0106    & 0       & 0.04       & 30               & 17          \\ 
30-39      & 0.0246    & 0.00066 & 0.08       & 20               & 20          \\ 
40-49      & 0.0340    & 0.00128 & 0.15       & 20               & 17          \\ 
50-59      & 0.0583    & 0.00207 & 0.25       & 20               & 15          \\ 
60-69      & 0.1175    & 0.00950 & 0.25       & 15              & 16          \\ 
70-79      & 0.2450    & 0.03864 & 0.25       & 15              & 10          \\ 
80+        & 0.2736    & 0.16859 & 0.25       & 15              & 0           \\
 
 \bottomrule 

\end{tabular}}
\begin{tablenotes}
\small
\item EMA base values and $\beta$ distributions are based on a report of 18 deaths among 86 cases of VIPIT, and 222 cases of VIPIT among 34 million vaccine recipients in Europe and the UK. NACI base values are based on NACI's rapid response published on March 29th, 2021. A probability distribution could not be calculated as numerators and denominators were not reported.\\
$R_0$ is the basic reproduction number.\\ $v_e$ is the effectiveness of vaccine against transmission.\\ $v_p$ is effectiveness of vaccine against severe disease.\\ Hospitalization, death, and Long COVID rates are number of people with the outcome divided by the number of concluded cases. Hospitalization and death rates for under 50 age groups are from BCCDC Situation Report Week 12, 2021. Death rates for age groups above 50 are from the preliminary dataset on confirmed cases of COVID-19, Public Health Agency of Canada (Table 13-26-0003) from January 1st, 2021 to April 9th, 2021 and accounts for the immunity already acquired in long-term care homes. Rates of Long COVID are Mulberry et al's estimations from data in Sudre et al. The proportion of essential workers by age was taken from the COVID Speak survey per Mulberry et al.\\
\end{tablenotes}

\label{harm-param}
\end{sidewaystable}

We assumed the first dose of the vaccine, regardless of the
manufacturer, to be, on average, 80\% effective against severe COVID-19
and 60\% effective in preventing transmission. We further assume that
all British Columbians will be offered a first dose of one of the
approved COVID-19 vaccines before July 1st, 2021, and a second dose
before the end of September 2021. We assumed the second dose to have no
effect other than prolonging the immunity acquired after the first dose
and posing a risk for VIPIT again. We did not consider the risk for
anaphylaxis, as all vaccines seem to have a similar risk in that regard
and the risk can be mitigated in the vaccination clinic. Population
estimates that were used in the model are summarized in Table 1.
COVID-19 age-based case fatality and hospitalization rates were obtained
from BC Centre for Disease Control (BCCDC) {[}12{]} and Public Health
Agency of Canada (Table: 13-26-0003){[}13{]}. For seniors, we used case
fatality rates from January 1st, 2021 to April 9th, 2021 to account for
the immunity already acquired in long-term care homes. Rates of Long
COVID are Mulberry et al's estimations from data in Sudre et al{[}14{]}.
The proportion of essential workers by age was taken from the COVID
Speak survey per Mulberry et al {[}10{]}. Population of BC in each group
was obtained from Statistics Canada {[}15{]}.

For harm-benefit analysis at an individual risk level, we weighed the
probability of VIPIT-related death or
\(P(\text{death})_{\text{VIPIT}} = P(\text{vaccine}) \times P(\text{VIPIT}|\text{vaccine}) \times P(\text{death}|\text{VIPIT})\),
against the average probability of contracting COVID-19 and dying from
it in each age groups, or
\(P(\text{death})_{\text{delayed vaccination}} = P(\text{COVID-19}) \times P(\text{death}|\text{COVID-19})\),
where \(P(\text{vaccine})\) is the probability of getting the AZ vaccine
(assumed to be 1 here), and \(P(\text{COVID-19})\) is the average
probability of contracting COVID-19 due to delayed vaccination from
April 1st, 2021 to July 1st, 2020.

We used results from our compartmental model to project mortality risk
from COVID-19 due to delayed vaccination, and conducted sensitivity
analyses around model assumptions as outlined in Table 1.

All the analysis was performed using publicly-available data and code.
This manuscript is produced by an open-source and reproducible R
Markdown script, which is available on
\href{https://github.com/aminadibi/astrazenecaVIPIT}{Github}.

\hypertarget{results}{%
\section{Results}\label{results}}

\hypertarget{model-validation}{%
\subsection{Model validation}\label{model-validation}}

\begin{figure}

{\centering \includegraphics[width=1\linewidth]{../figures/fig-validation} 

}

\caption{Face validity of model case counts}\label{fig:figValidation}
\end{figure}

Predicted epidemiological curve and age-stratified case counts showed
good agreement with observed counts reported by BC CDC, except for the
80 and above age category where the model underestimated case counts
(Figure 1), however, this age group had almost no implications on the
compared scenarios.

\hypertarget{harm-benefit-from-a-societal-perspective}{%
\subsection{Harm-benefit from a societal
perspective}\label{harm-benefit-from-a-societal-perspective}}

EMA evidence as of April 4th, 2021 suggests that if we immediately offer
a first dose of the AZ vaccine to all eligible front-line workers in BC,
the expected number of VIPIT-related deaths by the end of June 2021 is
0.338 {[}95\% CI 0.205-0.491{]}, which means the probability of
observing at least one VIPIT-related death in the same period is 28.6\%.
Adding the risk from the second dose, the expected number of
VIPIT-related deaths until the end of summer is 0.674 {[}95\% CI
0.413-0.987{]}. The probability of observing at least one VIPIT-related
death till the end of the summer will be 49\%.

NACI had based its analysis on the PEI estimates of a chance of 1 in
100,000 for VIPIT, and a mortality probability of 40\%, based on the
data that was available in late March. In this worst-case scenario, the
expected number of deaths in BC would be 1 after the first dose is
completed for all front-line workers and 2 after the second doses are
delivered. Details of the calculations can be found in Appendix A.

\begin{figure}

{\centering \includegraphics[width=1\linewidth]{../figures/fig-trajectoriesFull} 

}

\caption{Top Panel: Projection of the progression of the vaccination for different age groups and front-line workers (FLW). Bottom Panel: Projection of COVID-19 cases, hospitalizations, and deaths from January 1st to October 1st, 2021.}\label{fig:fig1}
\end{figure}

Figure 2 shows the progression of the vaccination campaign, as well as
projections for COVID-19 cases, hospitalizations, and deaths under the
two scenarios of immediately prioritizing front-line workers (A) and the
current scenario of asking them to wait to receive mRNA vaccines as part
of the current age-based vaccination program (B).

In our analysis, Scenario A led to 45755 fewer cases of COVID-19, 811
fewer hospitalizations, 127 fewer deaths, and 2321 fewer cases of Long
COVID, assuming \(R_0=1.35\). Appendix B includes results of the
sensitivity analysis for a wider range of values for \(R_0\) and the
effectiveness of the vaccine against transmission, \(v_e\).

\hypertarget{harm-benefit-from-an-individual-risk-perspective}{%
\subsection{Harm-benefit from an individual risk
perspective}\label{harm-benefit-from-an-individual-risk-perspective}}

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{CMAJOPen_files/figure-latex/covidvsvipit-1} 

}

\caption{ Comparison of excess mortality risk for different age groups based on the COVID-19 risk caused by delayed vaccination (B) and estimated residual COVID-19 and VIPIT risk (A) by the EMA and NACI}\label{fig:covidvsvipit}
\end{figure}

Figure 3 compares the risk of VIPIT-related mortality from 2 doses of
the AZ vaccine and residual risk from COVID-19, with the mortality risk
from COVID-19 due to delayed vaccination from April 1st to October 1st,
2021. We did the comparison under two scenarios of an \(R_0\) of 1.15 or
1.35, to represent different intensities for the third wave, or
alternatively to represent different geographical parts of the province
during the third wave. We calculated the mortality risk associated with
VIPIT using both the latest and most comprehensive evidence by EMA, and
the worst-case scenario using the evidence considered by NACI. Using EMA
estimates, we found that under both \(R_0\) scenarios, the mortality
risk due to COVID-19 to be much higher than the mortality risk
associated with VIPIT in those over 40. Mortality risk from COVID-19 was
also higher than that of VIPIT for the 30-39 age group, although the
difference was negligible under \(R_0\) of 1.15 scenario. For the 20-29
age group, the estimated mortality risk of vaccination with the AZ
vaccine was higher than that of COVID-19. Using the worst-case VIPIT
estimates considered by NACI, mortality risk from COVID-19 was
considerably higher than that of VIPIT for those over 60 in all areas
and those over 30 in high-risk areas (\(R_0=1.35\)).

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

In its analysis of AZ vaccine published on March 29th, 2021, NACI
weighed the risk of adverse events against the age-stratified risk of
mortality due to COVID-19, and concluded that the AZ vaccine should not
be used in adults under 55 years of age pending an overall
risk-assessment. Our analysis confirms that given the evidence available
in late March (a risk of 1 in 100,000 for VIPIT and a 40\% case
fatality) and the lower rates of transmission (i.e.~a lower \(R_0\)) at
that time, suspending the use of AZ vaccine in younger adults would have
been advisable. However, as of April 8th, 2021, the evidence has evolved
and the EMA is now reporting a risk of 1 in 153,000 for VIPIT and a 20\%
case fatality. These latest estimates together with a new wave of the
disease have changed the harm-benefit landscape considerably. In
addition, the benefits of the AZ vaccine go beyond preventing
COVID-related mortality and include protection against other possible
COVID-19 complications in younger adults including hospitalizations and
associated risk of venous thromboembolism (VTE; Rates are about 2 folds
higher in hospitalized COVID-19 patients than that of medical
non-COVID-19 inpatients {[}16{]}), and Long COVID, as well as preventing
onward transmission of the virus, as as suggested by the recent sharp
decline of COVID-19 cases in the UK {[}17{]} and possible emerging
signal in a recent observational healthcare worker/household study
{[}18{]}.

The UK vaccination program started on December 8th with the
Pfizer-BioNTech vaccine and was complemented with the AZ vaccine since
January 4th. The number of confirmed daily COVID-19 cases in the UK has
plummeted from about 60,000 cases a day in early January 2021 when a
national lockdown was imposed and about 3\% of the population had
received at least one vaccine dose, to about 11,000 cases per day on
February 22, 2021 when a roadmap to easing the lockdown was announced,
to about 6000 cases per day on March 8, 2021 when the first phase of
easing public health restrictions was commenced {[}19{]} and has
continuously declined since then to just under 2500 cases as of April
14th, 2021, when 61.4\% of the UK population had received one dose of a
COVID-19 vaccine {[}17{]}.

In addition to the death aversion resulting from strict public health
measures, based on a recent analysis by Public Health England and the
University of Warwick, it has been estimated that as of March 31, 2021,
10,400 deaths have been avoided in the UK solely due to the direct
implementation of a nationwide vaccination program (indirect effects
were not measured; 87.5\% of these averted deaths were in the 80+ years
old age group, 11.5\% of them in 70-79, and 1\% in 60-69 years old age
group) {[}20{]}. As about half of all vaccine doses administered in the
UK have been AZ vaccines, and based on the estimated AZ vaccine efficacy
of about 76\% against symptomatic COVID-19 and 64\% against any
NAAT-positive COVID-19 infection between 22 and 90 days after the first
dose {[}21{]}, and real-world single-dose AZ vaccine effectiveness of
about 60\% against symptomatic COVID-19 and 80\% against COVID-19
hospitalization {[}22{]}, it is clear that the AZ vaccine is effective
in reducing the overall burden of COVID-19.

Potential prevention of onward transmission with the AZ vaccine could be
especially critical for front-line workers during the current wave of
COVID cases. Of note, two recent studies from Toronto, Ontario have
shown that neighbourhoods with the highest proportion of front-line
workers had per capita COVID-19 case and death rates that were 2.5-3
folds higher than that of neighbourhoods with the lowest share of
front-line workers {[}24{]}.

Based on our analysis, immediately making the AZ vaccine available to
front-line workers is, assuming optimal uptake, net-beneficial by a wide
margin from a societal perspective. Our analysis from an individual risk
perspective shows that the risk of contracting COVID-19 and dying from
it due to delayed vaccination is considerably higher than the risk of
dying from VIPIT in those over 40, and also in those over 30 in
high-risk areas.

For a public health intervention to be deemed ethically acceptable,
being net-beneficial at a societal level is not enough in and of itself.
Not all interventions that are net-beneficial at a societal level are
net-beneficial for each member of the society, as those who carry the
burden of the risk of adverse events may not be the same people who reap
the benefits. We also recognize that many might intuitively consider
mortality due a public health intervention in an otherwise healthy
person to be ethically worse than failing to protect someone from
mortality due to COVID-19. While we are not going to solve the trolley
problem here, we believe that our conclusions hold regardless of the
position we take with respect to the \emph{doing vs.~allowing harm}
problem {[}25{]}, as long as the expected benefits outweigh the risk at
a personal level, as seems to be the case for most age groups in our
study.

Our analysis was based on the assumption that immediate deployment of
alternative mRNA vaccines for front-line workers was not logistically
feasible. If feasible, offering mRNA vaccines to front-line workers will
be more in line with the principle of reciprocity outlined in the BC
COVID-19 Ethical Decision-Making Framework {[}26{]}, and the more
general principle of justice in bioethics {[}27{]}, based on the fact
that as of April 10th, 2021, no VIPIT cases have been linked to COVID-19
mRNA vaccines. From a vaccine efficacy point of view, determining the
\emph{superiority} of one vaccine to the other is not straightforward;
there is more to the apparent but variable 4\%-33\% efficacy gap
(symptomatic COVID-19; 7-14 days after second dose) between mRNA and AZ
COVID-19 vaccines {[}28--31{]} than meets the eye, including differences
in study populations, settings, time periods (i.e.~different incidence
rates of COVID-19 from both non-variant of concern {[}VOC{]} and VOC
SARS-CoV-2) at different times of the year), and vaccine storage
requirements {[}32{]}. Importantly, these vaccines were comparable in
efficacy against severe COVID-19 in phase 3 trials {[}30,33{]}.
Considering emerging real-world vaccine effectiveness data, two studies
in the UK demonstrated that one dose of the Pfizer-BioNTech mRNA vaccine
or the AZ vaccine have a comparable performance in terms of reducing
rates of PCR-positive SARS-CoV-2 infection, symptomatic COVID-19, and
COVID-19-related hospitalizations {[}34,35{]}.

On April 14th, 2021, Health Canada issued an advisory concluding that
rare VIPIT events may be linked to the AZ COVID-19 vaccine and updated
its label accordingly. Health Canada did not identify any specific risk
factors and did not restrict the use of vaccine at this time {[}36{]}.
Health Canada's conclusions are consistent with our assumption that the
risk of VIPIT is uniform across age groups and pave the way for Canadian
provinces to make the AZ vaccine available to those under the age of 55.
However, while the risk from VIPIT might be similar across age group,
the risk from COVID-19 is not, and as such our age-based harm-benefit
approach remains valid. Our findings are further corroborated by the the
recent recommendation of the UK Joint Committee on Vaccination and
Immunisation (JCVI) that the benefits of the AZ vaccine far outweigh the
risk in 30 years old or older recipients {[}37{]}.

\hypertarget{limitations}{%
\section{Limitations}\label{limitations}}

Our analysis from an individual risk perspective was based on average
rates of COVID-19 and its related outcomes per age group. However, the
true risk within age groups is still heterogeneous and is affected by
many factors including but not limited to exposure, medical history,
work environment, and socioeconomic status.

Our analysis did not consider social aspects of vaccine roll-out such as
the effect of different roll-out strategies on uptake and vaccine
hesitancy, as they were beyond our expertise. However, we recognize that
each time a recommendation for vaccine safety is reversed, there might
be a penalty in public trust which could fuel vaccine hesitancy.
Potential for these effects should be weighed carefully by policy
makers.

Our analysis is based on currently available estimated rates of 1 in
million to 1 in 100,000 for VIPIT and might need correction should
higher rates of this complication be reported.

We have not considered potential sex differences in the risk for VIPIT.
Although cases identified to date have been predominantly female, it
remains unclear whether this was due to more females receiving the AZ
vaccine or due to an intrinsic difference in risk.

\hypertarget{conclusions}{%
\section{Conclusions}\label{conclusions}}

Current evidence suggests that benefits of immediate prioritization of
front-line workers for vaccination with the AZ vaccine far outweigh the
risk, both at a societal and at a personal level for those over 40 years
of age, and those over 30 years of age in high-risk areas. Ultimately,
in dynamic situations like this where the evidence is uncertain and
evolving, vaccine roll-out decisions are judgment calls that need to
take a complex network of medical, epidemiological, ethical, logistical,
and societal considerations into account.

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\newpage

\hypertarget{appendices}{%
\section{Appendices}\label{appendices}}

\hypertarget{calculations-for-expected-number-of-death}{%
\subsection{Calculations for expected number of
death}\label{calculations-for-expected-number-of-death}}

Assuming that BC allocates all 246,700 doses to front-line workers, we
can estimate the expected number of deaths due to VIPIT,
\(E(death)_{VIPIT}\), as shown below. To err on the side of caution, we
assume that each dose of the vaccine is independently associated with
the risk for VIPIT and that the risk of VIPIT is uniform across all age
groups. We also assume that there is enough uptake that BC is able to
administer all these doses.

\[
E(\text{death})_{\text{VIPIT}}  = d \times P(\text{VIPIT}|\text{vaccine}) \times P(\text{death}|\text{VIPIT})
\]

where d is the number of doses administered,
\(P(\text{VIPIT}|\text{vaccine})\) is the risk of VIPIT after receiving
each dose, and \(P(\text{death}|\text{VIPIT})\) is the case fatality for
VIPIT.

According to the most recent data from UK and EU submitted to
EudraVigilance (as of April 4th, 2021):

\[
\begin{aligned}
E(\text{death})_{\text{VIPIT}} & = d \times \frac{1}{153,000} \times \frac{21}{100} \\
& = 246,700 \times \frac{2.1}{1,530,000} \\
& \approx 0.338
\end{aligned}
\]

Considering both doses of the vaccine, we will have:

\[
\begin{aligned}
E(\text{death})_{\text{VIPIT}} & = d \times \frac{1}{153,000} \times \frac{21}{100} \\
& = 2 \times 246,700 \times \frac{2.1}{1,530,000} \\
& \approx 0.677
\end{aligned}
\]

NACI had based its analysis on the more pessimistic estimates of a
chance of 1 in 100,000 for VIPIT, and a mortality probability of 40\%.
In this worst-case scenario analysis, the expected number of deaths in
BC would be 1:

\[
\begin{aligned}
E(\text{death})_{\text{VIPIT-Worst Case}} & = d \times \frac{1}{100,000} \times \frac{40}{100} \\
& = 246,700 \times \frac{4}{1,000,000} \\
& \approx 1
\end{aligned}
\]

Considering both doses of the vaccine, the expected number of deaths in
BC would be 2.

\hypertarget{sensitivity-analysis}{%
\subsection{Sensitivity Analysis}\label{sensitivity-analysis}}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/fig-barplots.pdf"}
\caption{COVID-19 outcomes under different vaccination scenarios for different age groups and front-line workers (FLW) when $v_p=0.80$}
\end{center}
\end{figure}

Figure B1 summarizes projected COVID-19 case counts, hospitalizations,
and deaths, for a wider range of values for \(R_0\) and the
effectiveness of the vaccine against transmission, \(v_e\). Sensitivity
analysis on vaccine effectiveness against severe disease, \(v_p\), lead
to similar results and conclusions with a slight variation in number of
outcomes. As \(v_p\) increased, both the overall number of deaths and
the number of deaths prevented decreased. Specifically, under
\(v_p=0.90\), Scenario A led to 46779 fewer cases of COVID-19, 730 fewer
hospitalizations, 102 fewer deaths, and 2137 fewer cases of Long COVID,
assuming \(R_0\)= 1.35. Figures B2 to B5 summarize main results when
\(v_p=0.90\).

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.90/fig-validation.pdf"}
\caption{Observed and predicted case counts for different age groups when $v_p=0.90$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.90/fig-trajectoriesFull.pdf"}
\caption{Top Panel: Projection of the progression of the vaccination for different age groups and front-line workers (FLW). Bottom Panel: Projection of COVID-19 cases, hospitalizations, and deaths from January 1st to October 1st, 2021 for $v_p=0.90$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.90/fig3.pdf"}
\caption{Comparison of excess mortality risk for different age groups based on the COVID-19 risk caused by delayed vaccination (B) and estimated residual COVID-19 and VIPIT risk (A) by the EMA and NACI when $v_p=0.90$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.90/fig-barplots.pdf"}
\caption{COVID-19 outcomes under different vaccination scenarios for different age groups and front-line workers (FLW) when $v_p=0.90$}
\end{center}
\end{figure}

Under \(v_p=0.60\), Scenario A led to 43706 fewer cases of COVID-19, 910
fewer hospitalizations, 179 fewer deaths, and 2553 fewer cases of Long
COVID, assuming R 0 = 1.35. Figures B6 to B9 summarize main results when
\(v_p=0.60\).

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.60/fig-validation.pdf"}
\caption{Observed and predicted case counts for different age groups when $v_p=0.60$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.60/fig-trajectoriesFull.pdf"}
\caption{Top Panel: Projection of the progression of the vaccination for different age groups and front-line workers (FLW). Bottom Panel: Projection of COVID-19 cases, hospitalizations, and deaths from January 1st to October 1st, 2021 for $v_p=0.60$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.60/fig3.pdf"}
\caption{Comparison of excess mortality risk for different age groups based on the COVID-19 risk caused by delayed vaccination (B) and estimated residual COVID-19 and VIPIT risk (A) by the EMA and NACI when $v_p=0.90$}
\end{center}
\end{figure}

\begin{figure}[htb]
\begin{center}
\includegraphics[width=6in]{"../figures/vp0.60/fig-barplots.pdf"}
\caption{COVID-19 outcomes under different vaccination scenarios for different age groups and front-line workers (FLW) when $v_p=0.90$}
\end{center}
\end{figure}

\hypertarget{refs}{}
\begin{CSLReferences}{0}{0}
\leavevmode\hypertarget{ref-naci_naci_2021}{}%
\CSLLeftMargin{1. }
\CSLRightInline{NACI. {NACI} rapid response: {Recommended} use of
{AstraZeneca} {COVID}-19 vaccine in younger adults {[}Internet{]}.
National Advisory Committee on Immunization (NACI); 2021 Mar {[}cited
2021 Apr 3{]}. Available from:
\url{https://www.canada.ca/en/public-health/services/immunization/national-advisory-committee-on-immunization-naci/rapid-response-recommended-use-astrazeneca-covid-19-vaccine-younger-adults.html}}

\leavevmode\hypertarget{ref-greinacher_thrombotic_2021}{}%
\CSLLeftMargin{2. }
\CSLRightInline{Greinacher A, Thiele T, Warkentin TE, Weisser K, Kyrle
PA, Eichinger S. Thrombotic {Thrombocytopenia} after {ChAdOx1} {nCov}-19
{Vaccination}. New England Journal of Medicine {[}Internet{]}. 2021 Apr
{[}cited 2021 Apr 11{]};0(0):null. Available from:
\url{https://doi.org/10.1056/NEJMoa2104840}}

\leavevmode\hypertarget{ref-schultz_thrombosis_2021}{}%
\CSLLeftMargin{3. }
\CSLRightInline{Schultz NH, Sørvoll IH, Michelsen AE, Munthe LA,
Lund-Johansen F, Ahlen MT, et al. Thrombosis and {Thrombocytopenia}
after {ChAdOx1} {nCoV}-19 {Vaccination}. New England Journal of Medicine
{[}Internet{]}. 2021 Apr {[}cited 2021 Apr 11{]};0(0):null. Available
from: \url{https://doi.org/10.1056/NEJMoa2104882}}

\leavevmode\hypertarget{ref-ema_covid-19_2021}{}%
\CSLLeftMargin{4. }
\CSLRightInline{EMA. {COVID}-19 {Vaccine} {AstraZeneca}: Benefits still
outweigh the risks despite possible link to rare blood clots with low
blood platelets {[}Internet{]}. European Medicines Agency; 2021 Mar
{[}cited 2021 Apr 2{]}. Available from: \url{https://bit.ly/3s0pM8j}}

\leavevmode\hypertarget{ref-pei_covid-19_2021}{}%
\CSLLeftMargin{5. }
\CSLRightInline{PEI. {COVID}-19 {Vaccine} {AstraZeneca} - {Safety}
assessment result: {The} vaccine is safe and effective in the fight
against {COVID}-19 {[}Internet{]}. Paul-Ehrlich-Institut (PEI), Federal
Institute for Vaccines; Biomedicine; 2021 Mar {[}cited 2021 Apr 2{]}.
Available from: \url{https://bit.ly/3dJ7OSQ}}

\leavevmode\hypertarget{ref-mhra_coronavirus_2021}{}%
\CSLLeftMargin{6. }
\CSLRightInline{MHRA. Coronavirus vaccine - weekly summary of {Yellow}
{Card} reporting {[}Internet{]}. Medicines \& Healthcare Products
Regulatory Agency; 2021 Apr {[}cited 2021 Apr 3{]}. Available from:
\url{https://bit.ly/3dOW80z}}

\leavevmode\hypertarget{ref-mhra_mhra_2021}{}%
\CSLLeftMargin{7. }
\CSLRightInline{MHRA. {MHRA} issues new advice, concluding a possible
link between {COVID}-19 {Vaccine} {AstraZeneca} and extremely rare,
unlikely to occur blood clots {[}Internet{]}. GOV.UK. 2021 {[}cited 2021
Apr 8{]}. Available from: \url{https://bit.ly/39XSDUu}}

\leavevmode\hypertarget{ref-ema_astrazenecas_2021}{}%
\CSLLeftMargin{8. }
\CSLRightInline{EMA. {AstraZeneca}'s {COVID}-19 vaccine: {EMA} finds
possible link to very rare cases of unusual blood clots with low
platelets {[}Internet{]}. European Medicines Agency. 2021 {[}cited 2021
Apr 8{]}. Available from: \url{https://bit.ly/3s3ikJu}}

\leavevmode\hypertarget{ref-government_of_canada_vaccines_2021}{}%
\CSLLeftMargin{9. }
\CSLRightInline{Government of Canada. Vaccines for {COVID}-19:
{Shipments} and deliveries {[}Internet{]}. Government of Canada; 2021
Apr {[}cited 2021 Apr 3{]}. Available from:
\url{https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/prevention-risks/covid-19-vaccine-treatment/vaccine-rollout.html\#a4e}}

\leavevmode\hypertarget{ref-mulberry_vaccine_2021}{}%
\CSLLeftMargin{10. }
\CSLRightInline{Mulberry N, Tupper P, Kirwin E, McCabe C, Colijn C.
Vaccine {Rollout} {Strategies}: {The} {Case} for {Vaccinating}
{Essential} {Workers} {Early}. medRxiv {[}Internet{]}. 2021 Feb {[}cited
2021 Apr 3{]};2021.02.23.21252309. Available from:
\url{https://www.medrxiv.org/content/10.1101/2021.02.23.21252309v1}}

\leavevmode\hypertarget{ref-bubar_model-informed_2021}{}%
\CSLLeftMargin{11. }
\CSLRightInline{Bubar KM, Reinholt K, Kissler SM, Lipsitch M, Cobey S,
Grad YH, et al. Model-informed {COVID}-19 vaccine prioritization
strategies by age and serostatus. Science (New York, NY). 2021
Feb;371(6532):916--21. }

\leavevmode\hypertarget{ref-bccdc_british_2021}{}%
\CSLLeftMargin{12. }
\CSLRightInline{BCCDC. British {Columbia} ({BC}) {COVID}-19 {Situation}
{Report}. {Week} 12: {March} 21--{March} 27, 2021 {[}Internet{]}. 2021
Apr {[}cited 2021 Apr 10{]}. Available from:
\url{http://www.bccdc.ca/Health-Info-Site/Documents/COVID_sitrep/Week_12_2021_BC_COVID-19_Situation_Report.pdf}}

\leavevmode\hypertarget{ref-statistics_canada_preliminary_2021}{}%
\CSLLeftMargin{13. }
\CSLRightInline{Statistics Canada. Preliminary dataset on confirmed
cases of {COVID}-19, {Public} {Health} {Agency} of {Canada} {Tables}:
13-26-0003 {[}Internet{]}. 2021 {[}cited 2021 Apr 10{]}. Available from:
\url{https://www150.statcan.gc.ca/n1/en/catalogue/13260003}}

\leavevmode\hypertarget{ref-sudre_attributes_2021}{}%
\CSLLeftMargin{14. }
\CSLRightInline{Sudre CH, Murray B, Varsavsky T, Graham MS, Penfold RS,
Bowyer RC, et al. Attributes and predictors of long {COVID}. Nature
Medicine. 2021 Mar; }

\leavevmode\hypertarget{ref-statistics_canada_census_2017}{}%
\CSLLeftMargin{15. }
\CSLRightInline{Statistics Canada. Census {Profile}, 2016 {Census} -
{British} {Columbia} {[}{Province}{]} and {Canada} {[}{Country}{]}
{[}Internet{]}. 2017 {[}cited 2021 Apr 9{]}. Available from:
\url{https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/page.cfm?Lang=E\&Geo1=PR\&Code1=59\&Geo2=PR\&Code2=01\&SearchText=Canada\&SearchType=Begins\&SearchPR=01\&B1=All\&type=0}}

\leavevmode\hypertarget{ref-alberta_health_services_covid-19_2021}{}%
\CSLLeftMargin{16. }
\CSLRightInline{Alberta Health Services. {COVID}-19 {Scientific}
{Advisory} {Group} {Rapid} {Evidence} {Brief}: {Evidence} for screening
and preventing venous thromboembolic events in patients with {COVID}-19
{[}Internet{]}. 2021 Feb {[}cited 2021 Apr 11{]}. Available from:
\url{https://www.albertahealthservices.ca/assets/info/ppih/if-ppih-covid-19-sag-rapid-brief-screening-and-preventing-venous-thromboembolic-events.pdf}}

\leavevmode\hypertarget{ref-govuk_official_2021}{}%
\CSLLeftMargin{17. }
\CSLRightInline{GOV.uk. Official {UK} {Coronavirus} {Dashboard}
{[}Internet{]}. 2021 {[}cited 2021 Apr 14{]}. Available from:
\url{https://coronavirus.data.gov.uk}}

\leavevmode\hypertarget{ref-shah_effect_2021}{}%
\CSLLeftMargin{18. }
\CSLRightInline{Shah ASV, Gribben C, Bishop J, Hanlon P, Caldwell D,
Wood R, et al. Effect of vaccination on transmission of {COVID}-19: An
observational study in healthcare workers and their households. medRxiv
{[}Internet{]}. 2021 Mar {[}cited 2021 Apr 14{]};2021.03.11.21253275.
Available from:
\url{https://www.medrxiv.org/content/10.1101/2021.03.11.21253275v1}}

\leavevmode\hypertarget{ref-bbc_lockdown_2021}{}%
\CSLLeftMargin{19. }
\CSLRightInline{BBC. Lockdown: {Boris} {Johnson} unveils plan to end
{England} restrictions by 21 {June}. 2021 Feb {[}cited 2021 Apr 4{]};
Available from: \url{https://www.bbc.com/news/uk-56158405}}

\leavevmode\hypertarget{ref-public_health_england_impact_2021}{}%
\CSLLeftMargin{20. }
\CSLRightInline{Public Health England. Impact of {COVID}-19 vaccines on
mortality in {England} {[}Internet{]}. Public Health England; 2021 Mar
{[}cited 2021 Apr 9{]}. Available from:
\url{https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/977249/PHE_COVID-19_vaccine_impact_on_mortality_March.pdf}}

\leavevmode\hypertarget{ref-voysey_single-dose_2021}{}%
\CSLLeftMargin{21. }
\CSLRightInline{Voysey M, Clemens SAC, Madhi SA, Weckx LY, Folegatti PM,
Aley PK, et al. Single-dose administration and the influence of the
timing of the booster dose on immunogenicity and efficacy of {ChAdOx1}
{nCoV}-19 ({AZD1222}) vaccine: A pooled analysis of four randomised
trials. The Lancet {[}Internet{]}. 2021 Mar {[}cited 2021 Apr
4{]};397(10277):881--91. Available from:
\url{https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00432-3/abstract}}

\leavevmode\hypertarget{ref-public_health_england_1public_2021}{}%
\CSLLeftMargin{22. }
\CSLRightInline{Public Health England. {1Public} {Health} {England}
vaccine effectiveness report {[}Internet{]}. 2021 Mar {[}cited 2021 Apr
4{]}. Available from:
\url{https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/971017/SP_PH__VE_report_20210317_CC_JLB.pdf}}

\leavevmode\hypertarget{ref-chagla_characterizing_2021}{}%
\CSLLeftMargin{23. }
\CSLRightInline{Chagla Z, Ma H, Sander B, Baral SD, Mishra S.
Characterizing the disproportionate burden of {SARS}-{CoV}-2 variants of
concern among essential workers in the {Greater} {Toronto} {Area},
{Canada}. medRxiv {[}Internet{]}. 2021 Mar {[}cited 2021 Apr
4{]};2021.03.22.21254127. Available from:
\url{https://www.medrxiv.org/content/10.1101/2021.03.22.21254127v1}}

\leavevmode\hypertarget{ref-rao_disproportionate_2021}{}%
\CSLLeftMargin{24. }
\CSLRightInline{Rao A, Ma H, Moloney G, Kwong J, Juni P, Sander B, et
al. A disproportionate epidemic: {COVID}-19 cases and deaths among
essential workers in {Toronto}, {Canada}. 2021. }

\leavevmode\hypertarget{ref-woollard_doing_2016}{}%
\CSLLeftMargin{25. }
\CSLRightInline{Woollard F, Howard-Snyder F. Doing vs. {Allowing}
{Harm}. In: Zalta EN, editor. The {Stanford} {Encyclopedia} of
{Philosophy} {[}Internet{]}. Winter 2016. Metaphysics Research Lab,
Stanford University; 2016 {[}cited 2021 Apr 6{]}. Available from:
\url{https://plato.stanford.edu/archives/win2016/entries/doing-allowing/}}

\leavevmode\hypertarget{ref-bccdc_covid-19_2020}{}%
\CSLLeftMargin{26. }
\CSLRightInline{BCCDC. {COVID}-19 {Ethical} {Decision}-{Making}
{Framework} {[}Internet{]}. BC Ministry of Health; 2020 Mar {[}cited
2021 Apr 9{]}. Available from:
\url{https://www2.gov.bc.ca/assets/gov/health/about-bc-s-health-care-system/office-of-the-provincial-health-officer/covid-19/ethics_framework_for_covid_march_28_2020.pdf}}

\leavevmode\hypertarget{ref-mccormick_principles_2021}{}%
\CSLLeftMargin{27. }
\CSLRightInline{McCormick TR, Min D. Principles of {Bioethics}
{[}Internet{]}. 2021 {[}cited 2021 Apr 9{]}. Available from:
\url{https://depts.washington.edu/bhdept/ethics-medicine/bioethics-topics/articles/principles-bioethics}}

\leavevmode\hypertarget{ref-polack_safety_2020}{}%
\CSLLeftMargin{28. }
\CSLRightInline{Polack FP, Thomas SJ, Kitchin N, Absalon J, Gurtman A,
Lockhart S, et al. Safety and {Efficacy} of the {BNT162b2} {mRNA}
{Covid}-19 {Vaccine}. New England Journal of Medicine {[}Internet{]}.
2020 Dec {[}cited 2021 Apr 11{]};383(27):2603--15. Available from:
\url{https://doi.org/10.1056/NEJMoa2034577}}

\leavevmode\hypertarget{ref-baden_efficacy_2021}{}%
\CSLLeftMargin{29. }
\CSLRightInline{Baden LR, El Sahly HM, Essink B, Kotloff K, Frey S,
Novak R, et al. Efficacy and {Safety} of the {mRNA}-1273 {SARS}-{CoV}-2
{Vaccine}. New England Journal of Medicine {[}Internet{]}. 2021 Feb
{[}cited 2021 Apr 11{]};384(5):403--16. Available from:
\url{https://doi.org/10.1056/NEJMoa2035389}}

\leavevmode\hypertarget{ref-astrazeneca_azd1222_2021}{}%
\CSLLeftMargin{30. }
\CSLRightInline{AstraZeneca. {AZD1222} {US} {Phase} {III} primary
analysis confirms safety and efficacy {[}Internet{]}. 2021 {[}cited 2021
Apr 11{]}. Available from:
\url{https://www.astrazeneca.com/media-centre/press-releases/2021/azd1222-us-phase-iii-primary-analysis-confirms-safety-and-efficacy.html}}

\leavevmode\hypertarget{ref-emary_efficacy_2021}{}%
\CSLLeftMargin{31. }
\CSLRightInline{Emary KRW, Golubchik T, Aley PK, Ariani CV, Angus B,
Bibi S, et al. Efficacy of {ChAdOx1} {nCoV}-19 ({AZD1222}) vaccine
against {SARS}-{CoV}-2 variant of concern 202012/01 ({B}.1.1.7): An
exploratory analysis of a randomised controlled trial. The Lancet
{[}Internet{]}. 2021 Apr {[}cited 2021 Apr 11{]};397(10282):1351--62.
Available from:
\url{https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00628-0/abstract}}

\leavevmode\hypertarget{ref-ledford_why_2021}{}%
\CSLLeftMargin{32. }
\CSLRightInline{Ledford H. Why {COVID} vaccines are so difficult to
compare. Nature {[}Internet{]}. 2021 Feb {[}cited 2021 Apr
11{]};591(7848):16--7. Available from:
\url{https://www.nature.com/articles/d41586-021-00409-0}}

\leavevmode\hypertarget{ref-abdool_karim_new_2021}{}%
\CSLLeftMargin{33. }
\CSLRightInline{Abdool Karim SS, Oliveira T de. New {SARS}-{CoV}-2
{Variants} --- {Clinical}, {Public} {Health}, and {Vaccine}
{Implications}. New England Journal of Medicine {[}Internet{]}. 2021 Mar
{[}cited 2021 Apr 11{]};0(0):null. Available from:
\url{https://doi.org/10.1056/NEJMc2100362}}

\leavevmode\hypertarget{ref-shrotri_vaccine_2021}{}%
\CSLLeftMargin{34. }
\CSLRightInline{Shrotri M, Krutikov M, Palmer T, Giddings R, Azmi B,
Subbarao S, et al. Vaccine effectiveness of the first dose of {ChAdOx1}
{nCoV}-19 and {BNT162b2} against {SARS}-{CoV}-2 infection in residents
of {Long}-{Term} {Care} {Facilities} ({VIVALDI} study). medRxiv
{[}Internet{]}. 2021 Mar {[}cited 2021 Apr 11{]};2021.03.26.21254391.
Available from:
\url{https://www.medrxiv.org/content/10.1101/2021.03.26.21254391v1}}

\leavevmode\hypertarget{ref-jamie_lopez_bernal_early_2021}{}%
\CSLLeftMargin{35. }
\CSLRightInline{Jamie Lopez Bernal, Nick Andrews, Charlotte Gower, Julia
Stowe, Chris Robertson, Elise Tessier, et al. Early effectiveness of
{COVID}-19 vaccination with {BNT162b2} {mRNA} vaccine and {ChAdOx1}
adenovirus vector vaccine on symptomatic disease, hospitalisations and
mortality in older adults in {England} {{}} {medRxiv} {[}Internet{]}.
2021 {[}cited 2021 Apr 11{]}. Available from:
\url{https://www.medrxiv.org/content/10.1101/2021.03.01.21252652v1}}

\leavevmode\hypertarget{ref-health_canada_health_2021}{}%
\CSLLeftMargin{36. }
\CSLRightInline{Health Canada. Health {Canada} provides update on the
{AstraZeneca} and {COVISHIELD} {COVID}-19 vaccines {[}Internet{]}. 2021
{[}cited 2021 Apr 14{]}. Available from:
\url{https://healthycanadians.gc.ca/recall-alert-rappel-avis/hc-sc/2021/75389a-eng.php}}

\leavevmode\hypertarget{ref-jcvi_jcvi_2021}{}%
\CSLLeftMargin{37. }
\CSLRightInline{JCVI. {JCVI} statement on use of the {AstraZeneca}
{COVID}-19 vaccine: 7 {April} 2021 {[}Internet{]}. GOV.UK. 2021 {[}cited
2021 Apr 8{]}. Available from:
\url{https://www.gov.uk/government/publications/use-of-the-astrazeneca-covid-19-vaccine-jcvi-statement/jcvi-statement-on-use-of-the-astrazeneca-covid-19-vaccine-7-april-2021}}

\end{CSLReferences}


\end{document}

